on: workflow_dispatch

jobs:
  download-ffmpeg:
    name: Download FFmpeg
    runs-on: ubuntu-20.04

    steps:
      - run: |
          curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz --output ffmpeg.tar.xz --no-progress-meter

      - uses: actions/upload-artifact@v2
          with:
            name: ffmpeg
            path: ffmpeg.tar.xz
            if-no-files-found: error
            retention-days: 30
